name: Test

on: pull_request

jobs:
  lint:
    name: Linting and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: "3.x"

      - name: Install tox
        run: python -m pip install tox

      - name: Run test suite
        run: python -m tox -p -e flake8,black,yamllint

  test_tox:
    name: Run full tests
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        name: Install Python
        with:
          python-version: "3.x"

      - name: Install tox
        run: python -m pip install tox

      - name: Run test suite
        run: python -m tox -e py3
